"""
CampusClimb — Neural Text-to-Speech (TTS) Router
Provides real-time neural audio streaming via edge-tts (Microsoft Neural Voices).
No external API keys or billing required.
"""

import logging
import socket
from typing import Optional
import aiohttp
import edge_tts
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

logger = logging.getLogger("campusclimb.tts")

router = APIRouter(prefix="/api/v1/tts", tags=["TTS"])

DEFAULT_VOICE_EN = "en-IN-NeerjaNeural"  # Natural Indian English female
DEFAULT_VOICE_HI = "hi-IN-SwaraNeural"   # Natural Hindi female
ALT_VOICE_EN = "en-IN-PrabhatNeural"     # Indian English male
ALT_VOICE_HI = "hi-IN-MadhurNeural"      # Hindi male


class TTSRequest(BaseModel):
    text: str = Field(..., min_length=1, description="Text to synthesize to speech")
    lang: Optional[str] = Field("en", description="Language code: 'en', 'hi', or detected language")
    voice: Optional[str] = Field(None, description="Optional neural voice override")


def has_devanagari(text: str) -> bool:
    """Detect if text contains Devanagari Unicode characters (Hindi/Marathi/Sanskrit)."""
    return any("\u0900" <= ch <= "\u097f" for ch in text)


def resolve_voice(text: str, lang: Optional[str], requested_voice: Optional[str]) -> str:
    """Select the best neural voice based on language and script."""
    if requested_voice and requested_voice.strip():
        return requested_voice.strip()

    lang_lower = (lang or "").lower().strip()
    # Check for Hindi language code or Devanagari script presence
    if lang_lower in ["hi", "hin", "hindi", "hi-in"] or has_devanagari(text):
        return DEFAULT_VOICE_HI

    # Default to Indian English for natural bilingual/technical delivery
    return DEFAULT_VOICE_EN


async def generate_audio_stream(text: str, voice: str):
    """Asynchronously stream MP3 audio chunks generated by edge-tts directly in memory."""
    # Force IPv4 socket resolution on Windows to avoid IPv6 handshake delays
    connector = aiohttp.TCPConnector(family=socket.AF_INET)
    for attempt in range(2):
        try:
            communicate = edge_tts.Communicate(
                text,
                voice,
                connector=connector,
                connect_timeout=15,
                receive_timeout=60,
            )
            has_audio = False
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    has_audio = True
                    yield chunk["data"]

            if has_audio:
                return

            logger.warning("edge-tts stream completed with zero audio chunks for voice=%s (attempt %d)", voice, attempt + 1)
        except Exception as exc:
            logger.warning("edge-tts stream attempt %d failed for voice '%s': %s", attempt + 1, voice, exc)
            if attempt == 1:
                logger.error("All edge-tts attempts failed for voice '%s': %s", voice, exc, exc_info=True)
                raise


@router.post("", summary="Stream synthesized speech as an MP3 audio file")
async def text_to_speech(req: TTSRequest):
    """
    Synthesize text using neural voices (Microsoft Edge TTS engine)
    and return an audio/mpeg stream directly without saving to disk.
    """
    clean_text = req.text.strip()
    if not clean_text:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Text for speech synthesis cannot be empty.",
        )

    voice = resolve_voice(clean_text, req.lang, req.voice)
    logger.info("Generating neural TTS for %d chars using voice=%s (lang=%s)", len(clean_text), voice, req.lang)

    try:
        return StreamingResponse(
            generate_audio_stream(clean_text, voice),
            media_type="audio/mpeg",
            headers={
                "Content-Disposition": "inline; filename=speech.mp3",
                "Cache-Control": "no-cache, no-store, must-revalidate",
                "X-TTS-Voice": voice,
            },
        )
    except Exception as exc:
        logger.error("Failed to initialize TTS stream: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Neural TTS generation failed: {str(exc)}",
        ) from exc
